Repository oidc-soma/aerosquirrel, pull requests merged in 2023-08, with the labels that each got.

#35 FE Readme modified
  client/README.md
Labels: documentation

#36 Logout Function Added
  client/src/pages/Accounts.css
  client/src/pages/Accounts.tsx
  client/src/pages/Dashboard.css
  client/src/pages/Dashboard.tsx
  client/src/pages/Inventory.css
  client/src/pages/Inventory.tsx
Labels: enhancement

#38 Add AWS EC2 instances fetch functions
  go.mod
  go.sum
  server/models/price.go
  server/providers/aws/aws.go
  server/providers/aws/ec2/instances.go
  server/utils/calcdate.go
Labels: enhancement

#39 AWS 리소스 fetch api 수정
  server/handlers/resources_handler.go
  server/providers/aws/aws.go
  server/utils/calc_date.go
Labels: bug

#40 Dev/import csp
  go.mod
  go.sum
  server/handlers/resources_handler.go
  server/models/config.go
  server/providers/aws/aws.go
  server/providers/k8s/k8s.go
  server/providers/oci/oci.go
Labels: enhancement
